version: 2
jobs:
  macOS_swift_5.0:
    macos:
      xcode: "13.0.0"
    steps:
      - checkout
      - run: 
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test 2>&1 | xcpretty
      - run:
          name: Build release
          command: make build
workflows:
  version: 2
  workflow:
    jobs:
      - macOS_swift_5.0
